name: auracore
version: ${project.version}
main: org.ReDiego0.auracore.Auracore
api-version: '1.21'
author: ReDiego0
depend:
  - Towny
  - FastAsyncWorldEdit
  - DecentHolograms
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  auracc:
    description: Gestiona la moneda CC (Cristales de Carga)
    usage: /<command> [balance|add|take|set|pay]
    aliases: [cc, cristales]
    permission: auracore.cc
  auracore:
    description: Comando de administración de AuraCore
    usage: /<command> anomalia [place|remove]
    aliases: [ac]
    permission: auracore.admin